apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deployment
  name: myapp-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: nanajanashia/argocd-app:1.0
        name: myapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
